### ISSUE TITLE
support for psr-4 mandatory trailing backslash

### ISSUE THREAD

**Issue by lsalomon** [underground-works/atom-php-namespace-monkey#3]
```
{
    "autoload" : {
        "psr-4" : {
            "admin\\": "src/admin",
            "api\\" : "src/api",
            "phuzz\\" : "vendor/phuzz/src",
            "Psr\\Http\\Message\\": "vendor/psr/http-message/src"
        }
    }
}
```
If I create the `A/B/C.php` file in the `vendor/psr/http-message/src` directory, the namespace generated is `Psr\Http\Message\\A\B`

I wanted to contribute but can't push my branch. So here is a proposal to fix it, line 117 :
```
this.namespaces.push({ path, namespace: namespace.replace(/\\$/, '') })
```
instead of
```
this.namespaces.push({ path, namespace })
```

what do you think ?

**Comment by lsalomon** [comment]
great job by the way, this plugin does help !!

**Comment by itsgoingd** [comment]
Hey, thanks! Fixed it a bit differently, the plugin was expecting the autoload paths to end with a backslash, so we now check for that. Glad you are enjoying the package!
